### ISSUE TITLE
Boot cmd not run...

### ISSUE THREAD

**Issue by controlledentropy** [Magisk-Modules-Repo/djs#5]
I've tried different cmd and scripts, all of them do not work on device boot.

the djs.conf content:
---------------
versionCode=201906290
#2200 acc 45 44 && acc --set applyOnPlug usb/current_max:500000
#boot acc 80 70 && acc -s applyOnPlug 2000000
boot touch /sdcard/djstestbootshexe.txt
boot su -c echo Y > /sys/module/dwc3_msm/parameters/disable_host_mode
boot sh /sdcard/disotg.sh
--------------

device: Oneplus 3
rom: Havoc OS 3.8 android 10
magisk version: 20.4

now I use boot shell instead, hope fix : )

**Comment by bellrd** [comment]
Same issue asus zenform max pro m1 (Indian edition)

**Comment by VR-25** [comment]
Have you tried the latest release?

**Comment by rhayy** [comment]
Shouldn't these rules be in config.txt ?

**Comment by VR-25** [comment]
@controlledentropy, this works with the latest version.
However, some of your commands won't work, since Android's emulated storage is not ready that early.
```
boot touch /sdcard/djstestbootshexe.txt
boot sh /sdcard/disotg.sh
```
Even if you tried with a Magisk script or init.d, those would still fail.
You must wait until `/storage/emulated` is mounted and decrypted.
That's just how Android works.
`boot while [ ! -d /sdcard/Android ]; do sleep 10; done; touch /sdcard/djstestbootshexe.txt; sh /sdcard/disotg.sh`
